all: main ls cat date rm mkdir 

main: main.c
	gcc main.c -o main

ls: ls.c
	gcc ls.c -o ls

cat: cat.c
	gcc cat.c -o cat

date: date.c
	gcc date.c -o date

rm: rm.c
	gcc rm.c -o rm

mkdir: mkdir.c
	gcc mkdir.c -o mkdir

