all: sem_a sem_b mutex_a mutex_b

sem_a: sem_a.c
	gcc -o sem_a sem_a.c

sem_b: sem_b.c
	gcc -o sem_b sem_b.c

mutex_a: mutex_a.c
	gcc -o mutex_a mutex_a.c

mutex_b: mutex_b.c
	gcc -o mutex_b mutex_b.c