all: sem_a sem_b order_a order_b

sem_a: sem_a.c
	gcc -o sem_a sem_a.c

sem_b: sem_b.c
	gcc -o sem_b sem_b.c

mutex_a: mutex_a.c
	gcc -o order_a order_a.c

mutex_b: mutex_b.c
	gcc -o order_b order_b.c